import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { fromWei } from '../utils/common'
import { init, mintToken, checkUserToken, deposit, approveBank, withdraw } from '../utils/web3client'

const Home: NextPage = () => {

  useEffect(() => {
    init()
  }, [])

  const [balance, setBalance] = useState(0)
  const [isLoading, setIsLoading] = useState(false)

  const mint = (amount: number) => {
    setIsLoading(true)

    mintToken(`${amount}`)
      .then(tx => {
        console.log(tx)
        checkToken()
      })
      .catch(err => console.log(err))
      .finally(() => setIsLoading(false))
  }

  const checkToken = () => {
    setIsLoading(true)

    checkUserToken()
      .then(tx => {
        const balance = fromWei(tx)
        console.log(tx)
        setBalance(parseInt(balance))
      })
      .catch(err => console.log(err))
      .finally(() => setIsLoading(false))
  }

  const userApproveBank = async (amount: number) => {
    setIsLoading(true)

    await approveBank(`${amount}`)
      .then()
      .catch(err => console.log(err))
      .finally(() => setIsLoading(false))
  }

  const depositToken = async (amount: number) => {
    await userApproveBank(amount)
    setIsLoading(true)
    deposit(`${amount}`)
      .then(tx => {
        checkToken()
      })
      .catch(err => console.log(err))
      .finally(() => setIsLoading(false))
  }

  const withdrawToken = async (amount: number) => {
    setIsLoading(true)
    withdraw(`${amount}`)
      .then(tx => {
        checkToken()
      })
      .catch(err => console.log(err))
      .finally(() => setIsLoading(false))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
      </Head>
      <main>
        <div className="container">
          <h1>Hello Web3 : {balance}</h1>
          {isLoading && <h2>.........Loading.........</h2>}

          <div className="my-2">
            <button className="btn btn-primary" onClick={() => mint(1000)}>mint token</button>
          </div>
          <div className="my-2">
            <button className="btn btn-primary" onClick={() => checkToken()}>check my token</button>
          </div>
          <div className="my-2">
            <button className="btn btn-primary" onClick={() => depositToken(500)}>deposit</button>
          </div>
          <div className="my-2">
            <button className="btn btn-primary" onClick={() => withdrawToken(500)}>withdraw</button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
